name: Extension CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug extension files
        run: ./gradlew assemble
          
      - name: Upload extension files
        uses: actions/upload-artifact@v3
        with:
          name: android-appstudio-extension-files
          path: extension/build/extensions
